[package]
name = "NftProtocol"
version = "0.29.0"
published-at = "0x6cf3baf113ab6f1355a462def0bd3d4f49d5430e921755c1abef567f92e8ca43"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
# devnet-0.31.0
rev = "a63f425b9999c7fdfe483598720a9effc0acdc9e"

[dependencies.Originmate]
git = "https://github.com/Origin-Byte/originmate.git"
# devnet-0.31.0
rev = "76b1d610db3e779473f4cbc2a40de8d04b79c7a6"

[addresses]
nft_protocol = "0x6cf3baf113ab6f1355a462def0bd3d4f49d5430e921755c1abef567f92e8ca43"
